name: Clear Cache Cron

on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day (https://crontab.guru/once-a-day)
jobs:
  clear:
    name: Clear cache
    runs-on: ubuntu-latest
    steps:

    - uses: MyAlbum/purge-cache@v2
      with:
        accessed: true # Purge caches by their last accessed time (default)
        created: false # Purge caches by their created time (default)
        max-age: 604800 # Leave only caches accessed in the last 7 days (default)
