name: maintain dev

on: 
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: run clang-format
      run: find -type f \( -name *.h -o -name *.cpp \) | xargs clang-format -style=file -i

    - name: add files to cmake
      run: python ${{ github.workspace }}/scripts/cmake_generate.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: maintain
        branch: ${{ github.head_ref }}
